### ISSUE TITLE
Disabling exponents in fractions may yield many 0 in numbers.

### ISSUE THREAD

**Issue by chmike** [seagreen/Son#2]
This encoding, while deterministic, is then far from being compact.

**Comment by seagreen** [comment]
Absolutely a fair concern. Determinism is the top goal of the project, so we can't compromise that. It would be possible to switch from non-scientific to scientific notation for numbers of a certain size, but I don't think this is worth the extra complication. Even enormous numbers in the trillions don't take that many characters to encode.

**Comment by seagreen** [comment]
Closing because I'm pretty set on leaving scientific notation out. Hopefully that's the right decision.
