### ISSUE TITLE
Suggest UTF-8 only.

### ISSUE THREAD

**Issue by John-Nagle** [seagreen/Son#4]
JSON allows some obsolete encodings, such as UTF-16. All JSON parsers are supposed to accept UTF-8. It's probably appropriate to specify that only UTF-8 can be output. Byte order marks should be forbidden. 

32 bit Unicode escapes do not seem to be supported, but that's apparently a backwards-compatible thing with JSON.

**Comment by seagreen** [comment]
Great call: https://github.com/seagreen/Son/commit/86c4c2872c05c378f215bc31666a65a516e665f9

**Comment by seagreen** [comment]
I added a ["thanks" section](https://github.com/seagreen/Son#special-thanks), let me know if you want your link to go somewhere other than your GitHub.
