### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by jjpe** [seagreen/Son#5]
I'm wondering what the main use case is for this. Specifically, why would someone use this for m2m communication,  rather than e.g. Cap'n Proto or ProtoBuf?

**Comment by seagreen** [comment]
Great question. The general answer is: you shouldn't!

Cap'n Proto is awesome and if you can use that you probably should.

However, say you're already using JSON (maybe you're talking to a server that uses JSON, or you're writing some kind of data which must be formatted as JSON) then Son can be useful if you need to do machine processing of your data.

**Comment by jjpe** [comment]
Thanks for the explanation!
