### ISSUE TITLE
Support comments

### ISSUE THREAD

**Issue by xer0x** [seagreen/Son#9]
The ability to have comments in SON would be amazing. It's worth it, even if it isn't strictly in the subclass.

**Comment by seagreen** [comment]
Unfortunately that conflicts with the top priority of Son, which is to remain a subset of JSON.

I recommend you look into superset-of-JSON projects. [json5](http://json5.org/) is my favorite because it's fairly minimal.

**Comment by xer0x** [comment]
Too bad, but I appreciate your priorities. 👍
